version: "3"

services:
  composer:
    image: composer:latest
    user: 1000:1000
    volumes:
      - ./:/app
    working_dir: /app
  php81:
    build:
      context: docker/php81
    user: 1000:1000
    volumes:
      - ./:/app
    working_dir: /app
  php82:
    build:
      context: docker/php82
    user: 1000:1000
    volumes:
      - ./:/app
    working_dir: /app
  pest81:
    extends:
      service: php81
    environment:
      - XDEBUG_MODE=coverage
    entrypoint:
        - vendor/bin/pest
        - --coverage-html
        - .phpunit.coverage
        - --profile
  pest82:
    extends:
      service: php82
    environment:
      - XDEBUG_MODE=coverage
    entrypoint:
        - vendor/bin/pest
        - --coverage-html
        - .phpunit.coverage
        - --profile
  infection81:
    extends:
      service: php81
    entrypoint:
        - vendor/bin/infection
        - --threads=8
        - --logger-html=.infection.log.html
  infection82:
    extends:
      service: php82
    entrypoint:
        - vendor/bin/infection
        - --threads=8
        - --logger-html=.infection.log.html
  doctum:
    extends:
      service: php82
    entrypoint:
        - php
        - vendor/bin/doctum.php
        - update
        - ./doctum.php
  pint:
      extends:
          service: php82
      entrypoint:
          - vendor/bin/pint

